### ISSUE TITLE
Histogram : NaN values instead of negative values

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-d3#222]
### Description of the bug

Negative values are displayed as NaN values on `x` as well as `y` axis.

![image](https://github.com/gisaia/ARLAS-wui/assets/35499583/6132375f-7169-4d9a-8120-c607ca7de52e)

### Steps to reproduce

- Got to the [marine measures demo](https://demo.cloud.arlas.io/arlas/wui/?filter=%7B%7D&config_id=jYjGL41Wz0KIcunMNb3c&extend=9.951427139634035,53.79021086440039,12.92384458045359,54.66598023784812&vs=Current;Amonium).
- Open the analytic panel if not visible
- Scroll to the Salinity widget
- you see the distribution with NaN values

### If the issue was noticed in the demo workspace, please specify the collection and the field. Otherwise, please link the 2 ARLAS config files.

- collection: marine measures
- field: salinity

### Pointers
- Axes creation [code](https://github.com/gisaia/ARLAS-d3/blob/develop/src/histograms/charts/AbstractChart.ts#L419)

**Comment by MAudelGisaia** [comment]
without modification, the graph appears to display negative values correctly.
![image](https://github.com/gisaia/ARLAS-d3/assets/155989195/795f998b-b53d-43b5-b800-5adc55fac8aa)

**Comment by MAudelGisaia** [comment]
same from builder 



![Image](https://github.com/gisaia/ARLAS-d3/assets/155989195/384e698c-b8f2-4ec6-bfa3-903d66f9bcce)

**Comment by QuCMGisaia** [comment]
Already fixed in 11.1.1
